general {
    lock_cmd = hyprlock          # dbus/sysd lock command (loginctl lock-session)
    before_sleep_cmd = hyprlock
}

listener {
    timeout = 500                            # in seconds
		on-timeout = hyprlock
}
