background {
    monitor =
    path = ~/wallpapers/chill-mirror.jpg
    blur_passes = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    hide_cursor = true
}

label {
    monitor =
     text = cmd[update:1000] echo "$(date +"%-I:%M%p")"
    color = rgba(233, 190, 88, 0.75)
    font_size = 120
    font_family = SF Pro Display Bold
    position = 0, -140
    halign = center
    valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date '+%A, %d %B')</span>"
    color = rgba(180, 190, 254, 0.75)
    font_size = 30
    font_family = SF Pro Display Bold
    position = 0, 200
    halign = center
    valign = center
}

image {
    monitor =
    path = ~/.config/eww/dashboard/assets/pfp.png
    border_size = 0;
    size = 120
    position = 0, 60
    halign = center
    valign = center
}

label {
    monitor =
    text = Are you $USER?
    color = rgba(139, 233, 253, 0.65)
    font_size = 25
    font_family = SF Pro Display Bold
    position = 0, -70
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 290, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(30, 30, 46, 0.35)
    font_color = rgb(208, 135, 112)
    fade_on_empty = false
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99">Open Sesame</span></i>
    hide_input = false
    position = 0, -140
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/Scripts/songdetail.sh)"
    color = rgba(180, 118, 187, 0.75)
    font_size = 16
    font_family = JetBrains Mono Nerd, SF Pro Display Bold
    position = 0, 80
    halign = center
    valign = bottom
}
